stages:
  - build
  - deploy

build_homeoff-be:
  stage: build
  image: maven:3.8-openjdk-17
  script:
    - cd backend
    - mvn clean install
  artifacts:
    paths:
      - backend/target/ProyectoIntegradorEquipo4-0.0.1-SNAPSHOT.jar
  only:
    - test

deploy_homeoff-test-be:
  stage: deploy
  needs: [build_homeoff-be]
  image: alpine:3.11
  before_script:
    - apk update && apk add openssh-client bash
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$EC2_KEY_TEST_HOMEOFF_BE" | tr -d '\r' | ssh-add -
    - touch ~/.ssh/config
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - ssh-keyscan -H "$EC2_TEST_HOMEOFF_BE" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - scp backend/target/ProyectoIntegradorEquipo4-0.0.1-SNAPSHOT.jar $EC2_SSH_USER@$EC2_TEST_HOMEOFF_BE:~/
    - shh $EC2_SSH_USER@$EC2_TEST_HOMEOFF_BE "kill -9 $( lsof -i:8080 -t )"
    - ssh $EC2_SSH_USER@$EC2_TEST_HOMEOFF_BE "sudo systemctl restart ProyectoIntegradorEquipo4-0.0.1-SNAPSHOT.service"
  only:
    - test
